/********************************************************************************
** Form generated from reading UI file 'printmonthlyreport.ui'
**
** Created: Fri Feb 1 10:57:14 2013
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PRINTMONTHLYREPORT_H
#define UI_PRINTMONTHLYREPORT_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_CPrintMonthlyReport
{
public:
    QPushButton *btn96;
    QPushButton *btn99;
    QPushButton *btnRes0;
    QPushButton *btnRes1;
    QPushButton *btnRes2;
    QPushButton *btnRes3;
    QPushButton *btnRes7;
    QPushButton *btnRes5;
    QPushButton *btnRes6;
    QPushButton *btnRes4;
    QGroupBox *groupBox;
    QPushButton *btn35;
    QPushButton *btn2;
    QPushButton *btn32;
    QPushButton *btn44;
    QPushButton *btn39;
    QPushButton *btn38;
    QPushButton *btn47;
    QPushButton *btn11;
    QPushButton *btn22;
    QPushButton *btn33;
    QPushButton *btn21;
    QPushButton *btn4;
    QPushButton *btn74;
    QPushButton *btn76;
    QPushButton *btn43;
    QPushButton *btn28;
    QPushButton *btn60;
    QPushButton *btn29;
    QPushButton *btn68;
    QPushButton *btn65;
    QPushButton *btn71;
    QPushButton *btn72;
    QPushButton *btn49;
    QPushButton *btn30;
    QPushButton *btn42;
    QPushButton *btn19;
    QPushButton *btn34;
    QPushButton *btn61;
    QPushButton *btn79;
    QPushButton *btn25;
    QPushButton *btn45;
    QPushButton *btn56;
    QPushButton *btn78;
    QPushButton *btn83;
    QPushButton *btn55;
    QPushButton *btn7;
    QPushButton *btn5;
    QPushButton *btn69;
    QPushButton *btn13;
    QPushButton *btn36;
    QPushButton *btn15;
    QPushButton *btn18;
    QPushButton *btn8;
    QPushButton *btn31;
    QPushButton *btn14;
    QPushButton *btn27;
    QPushButton *btn9;
    QPushButton *btn57;
    QPushButton *btn48;
    QPushButton *btn51;
    QPushButton *btn67;
    QPushButton *btn52;
    QPushButton *btn77;
    QPushButton *btn0;
    QPushButton *btn40;
    QPushButton *btn53;
    QPushButton *btn6;
    QPushButton *btn81;
    QPushButton *btn46;
    QPushButton *btn16;
    QPushButton *btn66;
    QPushButton *btn26;
    QPushButton *btn64;
    QPushButton *btn24;
    QPushButton *btn62;
    QPushButton *btn84;
    QPushButton *btn86;
    QPushButton *btn12;
    QPushButton *btn58;
    QPushButton *btn3;
    QPushButton *btn82;
    QPushButton *btn23;
    QPushButton *btn37;
    QPushButton *btn80;
    QPushButton *btn50;
    QPushButton *btn70;
    QPushButton *btn73;
    QPushButton *btn1;
    QPushButton *btn17;
    QPushButton *btn41;
    QPushButton *btn85;
    QPushButton *btn54;
    QPushButton *btn59;
    QPushButton *btn10;
    QPushButton *btn75;
    QPushButton *btn63;
    QPushButton *btn20;
    QPushButton *btn87;
    QPushButton *btnClear;

    void setupUi(QFrame *CPrintMonthlyReport)
    {
        if (CPrintMonthlyReport->objectName().isEmpty())
            CPrintMonthlyReport->setObjectName(QString::fromUtf8("CPrintMonthlyReport"));
        CPrintMonthlyReport->resize(639, 308);
        CPrintMonthlyReport->setStyleSheet(QString::fromUtf8(""));
        CPrintMonthlyReport->setFrameShape(QFrame::StyledPanel);
        CPrintMonthlyReport->setFrameShadow(QFrame::Raised);
        btn96 = new QPushButton(CPrintMonthlyReport);
        btn96->setObjectName(QString::fromUtf8("btn96"));
        btn96->setGeometry(QRect(430, 265, 61, 30));
        QFont font;
        font.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font.setPointSize(16);
        btn96->setFont(font);
        btn96->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn99 = new QPushButton(CPrintMonthlyReport);
        btn99->setObjectName(QString::fromUtf8("btn99"));
        btn99->setGeometry(QRect(540, 265, 61, 30));
        btn99->setFont(font);
        btn99->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btnRes0 = new QPushButton(CPrintMonthlyReport);
        btnRes0->setObjectName(QString::fromUtf8("btnRes0"));
        btnRes0->setGeometry(QRect(20, 12, 37, 37));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font1.setPointSize(25);
        btnRes0->setFont(font1);
        btnRes0->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes1 = new QPushButton(CPrintMonthlyReport);
        btnRes1->setObjectName(QString::fromUtf8("btnRes1"));
        btnRes1->setGeometry(QRect(60, 12, 37, 37));
        btnRes1->setFont(font1);
        btnRes1->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes2 = new QPushButton(CPrintMonthlyReport);
        btnRes2->setObjectName(QString::fromUtf8("btnRes2"));
        btnRes2->setGeometry(QRect(100, 12, 37, 37));
        btnRes2->setFont(font1);
        btnRes2->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes3 = new QPushButton(CPrintMonthlyReport);
        btnRes3->setObjectName(QString::fromUtf8("btnRes3"));
        btnRes3->setGeometry(QRect(140, 12, 37, 37));
        btnRes3->setFont(font1);
        btnRes3->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes7 = new QPushButton(CPrintMonthlyReport);
        btnRes7->setObjectName(QString::fromUtf8("btnRes7"));
        btnRes7->setGeometry(QRect(300, 12, 37, 37));
        btnRes7->setFont(font1);
        btnRes7->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes5 = new QPushButton(CPrintMonthlyReport);
        btnRes5->setObjectName(QString::fromUtf8("btnRes5"));
        btnRes5->setGeometry(QRect(220, 12, 37, 37));
        btnRes5->setFont(font1);
        btnRes5->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes6 = new QPushButton(CPrintMonthlyReport);
        btnRes6->setObjectName(QString::fromUtf8("btnRes6"));
        btnRes6->setGeometry(QRect(260, 12, 37, 37));
        btnRes6->setFont(font1);
        btnRes6->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        btnRes4 = new QPushButton(CPrintMonthlyReport);
        btnRes4->setObjectName(QString::fromUtf8("btnRes4"));
        btnRes4->setGeometry(QRect(180, 12, 37, 37));
        btnRes4->setFont(font1);
        btnRes4->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"background-color: rgb(20, 37, 81);\n"
"color: rgb(255, 255, 255);"));
        groupBox = new QGroupBox(CPrintMonthlyReport);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 56, 621, 201));
        groupBox->setStyleSheet(QString::fromUtf8("background-image:url(none);\n"
"border-color: rgb(0, 170, 0);"));
        groupBox->setCheckable(false);
        btn35 = new QPushButton(groupBox);
        btn35->setObjectName(QString::fromUtf8("btn35"));
        btn35->setGeometry(QRect(130, 70, 30, 30));
        QFont font2;
        font2.setPointSize(12);
        btn35->setFont(font2);
        btn35->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn2 = new QPushButton(groupBox);
        btn2->setObjectName(QString::fromUtf8("btn2"));
        btn2->setGeometry(QRect(70, 10, 30, 30));
        btn2->setFont(font2);
        btn2->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn32 = new QPushButton(groupBox);
        btn32->setObjectName(QString::fromUtf8("btn32"));
        btn32->setGeometry(QRect(40, 70, 30, 30));
        btn32->setFont(font2);
        btn32->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn44 = new QPushButton(groupBox);
        btn44->setObjectName(QString::fromUtf8("btn44"));
        btn44->setGeometry(QRect(400, 70, 30, 30));
        btn44->setFont(font2);
        btn44->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn39 = new QPushButton(groupBox);
        btn39->setObjectName(QString::fromUtf8("btn39"));
        btn39->setGeometry(QRect(250, 70, 30, 30));
        btn39->setFont(font2);
        btn39->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn38 = new QPushButton(groupBox);
        btn38->setObjectName(QString::fromUtf8("btn38"));
        btn38->setGeometry(QRect(220, 70, 30, 30));
        btn38->setFont(font2);
        btn38->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn47 = new QPushButton(groupBox);
        btn47->setObjectName(QString::fromUtf8("btn47"));
        btn47->setGeometry(QRect(490, 70, 30, 30));
        btn47->setFont(font2);
        btn47->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn11 = new QPushButton(groupBox);
        btn11->setObjectName(QString::fromUtf8("btn11"));
        btn11->setGeometry(QRect(340, 10, 30, 30));
        btn11->setFont(font2);
        btn11->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn22 = new QPushButton(groupBox);
        btn22->setObjectName(QString::fromUtf8("btn22"));
        btn22->setGeometry(QRect(70, 40, 30, 30));
        btn22->setFont(font2);
        btn22->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn33 = new QPushButton(groupBox);
        btn33->setObjectName(QString::fromUtf8("btn33"));
        btn33->setGeometry(QRect(70, 70, 30, 30));
        btn33->setFont(font2);
        btn33->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn21 = new QPushButton(groupBox);
        btn21->setObjectName(QString::fromUtf8("btn21"));
        btn21->setGeometry(QRect(40, 40, 30, 30));
        btn21->setFont(font2);
        btn21->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn4 = new QPushButton(groupBox);
        btn4->setObjectName(QString::fromUtf8("btn4"));
        btn4->setGeometry(QRect(130, 10, 30, 30));
        btn4->setFont(font2);
        btn4->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn74 = new QPushButton(groupBox);
        btn74->setObjectName(QString::fromUtf8("btn74"));
        btn74->setGeometry(QRect(190, 160, 30, 30));
        btn74->setFont(font2);
        btn74->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn76 = new QPushButton(groupBox);
        btn76->setObjectName(QString::fromUtf8("btn76"));
        btn76->setGeometry(QRect(250, 160, 30, 30));
        btn76->setFont(font2);
        btn76->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn43 = new QPushButton(groupBox);
        btn43->setObjectName(QString::fromUtf8("btn43"));
        btn43->setGeometry(QRect(370, 70, 30, 30));
        btn43->setFont(font2);
        btn43->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn28 = new QPushButton(groupBox);
        btn28->setObjectName(QString::fromUtf8("btn28"));
        btn28->setGeometry(QRect(250, 40, 30, 30));
        btn28->setFont(font2);
        btn28->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn60 = new QPushButton(groupBox);
        btn60->setObjectName(QString::fromUtf8("btn60"));
        btn60->setGeometry(QRect(100, 130, 30, 30));
        btn60->setFont(font2);
        btn60->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn29 = new QPushButton(groupBox);
        btn29->setObjectName(QString::fromUtf8("btn29"));
        btn29->setGeometry(QRect(280, 40, 30, 30));
        btn29->setFont(font2);
        btn29->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn68 = new QPushButton(groupBox);
        btn68->setObjectName(QString::fromUtf8("btn68"));
        btn68->setGeometry(QRect(10, 160, 30, 30));
        btn68->setFont(font2);
        btn68->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn65 = new QPushButton(groupBox);
        btn65->setObjectName(QString::fromUtf8("btn65"));
        btn65->setGeometry(QRect(250, 130, 30, 30));
        btn65->setFont(font2);
        btn65->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn71 = new QPushButton(groupBox);
        btn71->setObjectName(QString::fromUtf8("btn71"));
        btn71->setGeometry(QRect(100, 160, 30, 30));
        btn71->setFont(font2);
        btn71->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn72 = new QPushButton(groupBox);
        btn72->setObjectName(QString::fromUtf8("btn72"));
        btn72->setGeometry(QRect(130, 160, 30, 30));
        btn72->setFont(font2);
        btn72->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn49 = new QPushButton(groupBox);
        btn49->setObjectName(QString::fromUtf8("btn49"));
        btn49->setGeometry(QRect(550, 70, 30, 30));
        btn49->setFont(font2);
        btn49->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn30 = new QPushButton(groupBox);
        btn30->setObjectName(QString::fromUtf8("btn30"));
        btn30->setGeometry(QRect(310, 40, 30, 30));
        btn30->setFont(font2);
        btn30->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn42 = new QPushButton(groupBox);
        btn42->setObjectName(QString::fromUtf8("btn42"));
        btn42->setGeometry(QRect(340, 70, 30, 30));
        btn42->setFont(font2);
        btn42->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn19 = new QPushButton(groupBox);
        btn19->setObjectName(QString::fromUtf8("btn19"));
        btn19->setGeometry(QRect(580, 10, 30, 30));
        btn19->setFont(font2);
        btn19->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn34 = new QPushButton(groupBox);
        btn34->setObjectName(QString::fromUtf8("btn34"));
        btn34->setGeometry(QRect(100, 70, 30, 30));
        btn34->setFont(font2);
        btn34->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn61 = new QPushButton(groupBox);
        btn61->setObjectName(QString::fromUtf8("btn61"));
        btn61->setGeometry(QRect(130, 130, 30, 30));
        btn61->setFont(font2);
        btn61->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn79 = new QPushButton(groupBox);
        btn79->setObjectName(QString::fromUtf8("btn79"));
        btn79->setGeometry(QRect(340, 160, 30, 30));
        btn79->setFont(font2);
        btn79->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn25 = new QPushButton(groupBox);
        btn25->setObjectName(QString::fromUtf8("btn25"));
        btn25->setGeometry(QRect(160, 40, 30, 30));
        btn25->setFont(font2);
        btn25->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn45 = new QPushButton(groupBox);
        btn45->setObjectName(QString::fromUtf8("btn45"));
        btn45->setGeometry(QRect(430, 70, 30, 30));
        btn45->setFont(font2);
        btn45->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn56 = new QPushButton(groupBox);
        btn56->setObjectName(QString::fromUtf8("btn56"));
        btn56->setGeometry(QRect(160, 100, 30, 30));
        btn56->setFont(font2);
        btn56->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn78 = new QPushButton(groupBox);
        btn78->setObjectName(QString::fromUtf8("btn78"));
        btn78->setGeometry(QRect(310, 160, 30, 30));
        btn78->setFont(font2);
        btn78->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn83 = new QPushButton(groupBox);
        btn83->setObjectName(QString::fromUtf8("btn83"));
        btn83->setGeometry(QRect(460, 160, 30, 30));
        btn83->setFont(font2);
        btn83->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn55 = new QPushButton(groupBox);
        btn55->setObjectName(QString::fromUtf8("btn55"));
        btn55->setGeometry(QRect(130, 100, 30, 30));
        btn55->setFont(font2);
        btn55->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn7 = new QPushButton(groupBox);
        btn7->setObjectName(QString::fromUtf8("btn7"));
        btn7->setGeometry(QRect(220, 10, 30, 30));
        btn7->setFont(font2);
        btn7->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn5 = new QPushButton(groupBox);
        btn5->setObjectName(QString::fromUtf8("btn5"));
        btn5->setGeometry(QRect(160, 10, 30, 30));
        btn5->setFont(font2);
        btn5->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn69 = new QPushButton(groupBox);
        btn69->setObjectName(QString::fromUtf8("btn69"));
        btn69->setGeometry(QRect(40, 160, 30, 30));
        btn69->setFont(font2);
        btn69->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn13 = new QPushButton(groupBox);
        btn13->setObjectName(QString::fromUtf8("btn13"));
        btn13->setGeometry(QRect(400, 10, 30, 30));
        btn13->setFont(font2);
        btn13->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn36 = new QPushButton(groupBox);
        btn36->setObjectName(QString::fromUtf8("btn36"));
        btn36->setGeometry(QRect(160, 70, 30, 30));
        btn36->setFont(font2);
        btn36->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn15 = new QPushButton(groupBox);
        btn15->setObjectName(QString::fromUtf8("btn15"));
        btn15->setGeometry(QRect(460, 10, 30, 30));
        btn15->setFont(font2);
        btn15->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn18 = new QPushButton(groupBox);
        btn18->setObjectName(QString::fromUtf8("btn18"));
        btn18->setGeometry(QRect(550, 10, 30, 30));
        btn18->setFont(font2);
        btn18->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn8 = new QPushButton(groupBox);
        btn8->setObjectName(QString::fromUtf8("btn8"));
        btn8->setGeometry(QRect(250, 10, 30, 30));
        btn8->setFont(font2);
        btn8->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn31 = new QPushButton(groupBox);
        btn31->setObjectName(QString::fromUtf8("btn31"));
        btn31->setGeometry(QRect(10, 70, 30, 30));
        btn31->setFont(font2);
        btn31->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn14 = new QPushButton(groupBox);
        btn14->setObjectName(QString::fromUtf8("btn14"));
        btn14->setGeometry(QRect(430, 10, 30, 30));
        btn14->setFont(font2);
        btn14->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn27 = new QPushButton(groupBox);
        btn27->setObjectName(QString::fromUtf8("btn27"));
        btn27->setGeometry(QRect(220, 40, 30, 30));
        btn27->setFont(font2);
        btn27->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn9 = new QPushButton(groupBox);
        btn9->setObjectName(QString::fromUtf8("btn9"));
        btn9->setGeometry(QRect(280, 10, 30, 30));
        btn9->setFont(font2);
        btn9->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn57 = new QPushButton(groupBox);
        btn57->setObjectName(QString::fromUtf8("btn57"));
        btn57->setGeometry(QRect(10, 130, 30, 30));
        btn57->setFont(font2);
        btn57->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn48 = new QPushButton(groupBox);
        btn48->setObjectName(QString::fromUtf8("btn48"));
        btn48->setGeometry(QRect(520, 70, 30, 30));
        btn48->setFont(font2);
        btn48->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn51 = new QPushButton(groupBox);
        btn51->setObjectName(QString::fromUtf8("btn51"));
        btn51->setGeometry(QRect(10, 100, 30, 30));
        btn51->setFont(font2);
        btn51->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn67 = new QPushButton(groupBox);
        btn67->setObjectName(QString::fromUtf8("btn67"));
        btn67->setGeometry(QRect(310, 130, 30, 30));
        btn67->setFont(font2);
        btn67->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn52 = new QPushButton(groupBox);
        btn52->setObjectName(QString::fromUtf8("btn52"));
        btn52->setGeometry(QRect(40, 100, 30, 30));
        btn52->setFont(font2);
        btn52->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn77 = new QPushButton(groupBox);
        btn77->setObjectName(QString::fromUtf8("btn77"));
        btn77->setGeometry(QRect(280, 160, 30, 30));
        btn77->setFont(font2);
        btn77->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn0 = new QPushButton(groupBox);
        btn0->setObjectName(QString::fromUtf8("btn0"));
        btn0->setGeometry(QRect(10, 10, 30, 30));
        btn0->setFont(font2);
        btn0->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn40 = new QPushButton(groupBox);
        btn40->setObjectName(QString::fromUtf8("btn40"));
        btn40->setGeometry(QRect(280, 70, 30, 30));
        btn40->setFont(font2);
        btn40->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn53 = new QPushButton(groupBox);
        btn53->setObjectName(QString::fromUtf8("btn53"));
        btn53->setGeometry(QRect(70, 100, 30, 30));
        btn53->setFont(font2);
        btn53->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn6 = new QPushButton(groupBox);
        btn6->setObjectName(QString::fromUtf8("btn6"));
        btn6->setGeometry(QRect(190, 10, 30, 30));
        btn6->setFont(font2);
        btn6->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn81 = new QPushButton(groupBox);
        btn81->setObjectName(QString::fromUtf8("btn81"));
        btn81->setGeometry(QRect(400, 160, 30, 30));
        btn81->setFont(font2);
        btn81->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn46 = new QPushButton(groupBox);
        btn46->setObjectName(QString::fromUtf8("btn46"));
        btn46->setGeometry(QRect(460, 70, 30, 30));
        btn46->setFont(font2);
        btn46->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn16 = new QPushButton(groupBox);
        btn16->setObjectName(QString::fromUtf8("btn16"));
        btn16->setGeometry(QRect(490, 10, 30, 30));
        btn16->setFont(font2);
        btn16->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn66 = new QPushButton(groupBox);
        btn66->setObjectName(QString::fromUtf8("btn66"));
        btn66->setGeometry(QRect(280, 130, 30, 30));
        btn66->setFont(font2);
        btn66->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn26 = new QPushButton(groupBox);
        btn26->setObjectName(QString::fromUtf8("btn26"));
        btn26->setGeometry(QRect(190, 40, 30, 30));
        btn26->setFont(font2);
        btn26->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn64 = new QPushButton(groupBox);
        btn64->setObjectName(QString::fromUtf8("btn64"));
        btn64->setGeometry(QRect(220, 130, 30, 30));
        btn64->setFont(font2);
        btn64->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn24 = new QPushButton(groupBox);
        btn24->setObjectName(QString::fromUtf8("btn24"));
        btn24->setGeometry(QRect(130, 40, 30, 30));
        btn24->setFont(font2);
        btn24->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn62 = new QPushButton(groupBox);
        btn62->setObjectName(QString::fromUtf8("btn62"));
        btn62->setGeometry(QRect(160, 130, 30, 30));
        btn62->setFont(font2);
        btn62->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn84 = new QPushButton(groupBox);
        btn84->setObjectName(QString::fromUtf8("btn84"));
        btn84->setGeometry(QRect(490, 160, 30, 30));
        btn84->setFont(font2);
        btn84->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn86 = new QPushButton(groupBox);
        btn86->setObjectName(QString::fromUtf8("btn86"));
        btn86->setGeometry(QRect(550, 160, 30, 30));
        btn86->setFont(font2);
        btn86->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn12 = new QPushButton(groupBox);
        btn12->setObjectName(QString::fromUtf8("btn12"));
        btn12->setGeometry(QRect(370, 10, 30, 30));
        btn12->setFont(font2);
        btn12->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn58 = new QPushButton(groupBox);
        btn58->setObjectName(QString::fromUtf8("btn58"));
        btn58->setGeometry(QRect(40, 130, 30, 30));
        btn58->setFont(font2);
        btn58->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn3 = new QPushButton(groupBox);
        btn3->setObjectName(QString::fromUtf8("btn3"));
        btn3->setGeometry(QRect(100, 10, 30, 30));
        btn3->setFont(font2);
        btn3->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn82 = new QPushButton(groupBox);
        btn82->setObjectName(QString::fromUtf8("btn82"));
        btn82->setGeometry(QRect(430, 160, 30, 30));
        btn82->setFont(font2);
        btn82->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn23 = new QPushButton(groupBox);
        btn23->setObjectName(QString::fromUtf8("btn23"));
        btn23->setGeometry(QRect(100, 40, 30, 30));
        btn23->setFont(font2);
        btn23->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn37 = new QPushButton(groupBox);
        btn37->setObjectName(QString::fromUtf8("btn37"));
        btn37->setGeometry(QRect(190, 70, 30, 30));
        btn37->setFont(font2);
        btn37->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn80 = new QPushButton(groupBox);
        btn80->setObjectName(QString::fromUtf8("btn80"));
        btn80->setGeometry(QRect(370, 160, 30, 30));
        btn80->setFont(font2);
        btn80->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn50 = new QPushButton(groupBox);
        btn50->setObjectName(QString::fromUtf8("btn50"));
        btn50->setGeometry(QRect(580, 70, 30, 30));
        btn50->setFont(font2);
        btn50->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn70 = new QPushButton(groupBox);
        btn70->setObjectName(QString::fromUtf8("btn70"));
        btn70->setGeometry(QRect(70, 160, 30, 30));
        btn70->setFont(font2);
        btn70->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn73 = new QPushButton(groupBox);
        btn73->setObjectName(QString::fromUtf8("btn73"));
        btn73->setGeometry(QRect(160, 160, 30, 30));
        btn73->setFont(font2);
        btn73->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn1 = new QPushButton(groupBox);
        btn1->setObjectName(QString::fromUtf8("btn1"));
        btn1->setGeometry(QRect(40, 10, 30, 30));
        btn1->setFont(font2);
        btn1->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn17 = new QPushButton(groupBox);
        btn17->setObjectName(QString::fromUtf8("btn17"));
        btn17->setGeometry(QRect(520, 10, 30, 30));
        btn17->setFont(font2);
        btn17->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn41 = new QPushButton(groupBox);
        btn41->setObjectName(QString::fromUtf8("btn41"));
        btn41->setGeometry(QRect(310, 70, 30, 30));
        btn41->setFont(font2);
        btn41->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn85 = new QPushButton(groupBox);
        btn85->setObjectName(QString::fromUtf8("btn85"));
        btn85->setGeometry(QRect(520, 160, 30, 30));
        btn85->setFont(font2);
        btn85->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn54 = new QPushButton(groupBox);
        btn54->setObjectName(QString::fromUtf8("btn54"));
        btn54->setGeometry(QRect(100, 100, 30, 30));
        btn54->setFont(font2);
        btn54->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn59 = new QPushButton(groupBox);
        btn59->setObjectName(QString::fromUtf8("btn59"));
        btn59->setGeometry(QRect(70, 130, 30, 30));
        btn59->setFont(font2);
        btn59->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn10 = new QPushButton(groupBox);
        btn10->setObjectName(QString::fromUtf8("btn10"));
        btn10->setGeometry(QRect(310, 10, 30, 30));
        btn10->setFont(font2);
        btn10->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn75 = new QPushButton(groupBox);
        btn75->setObjectName(QString::fromUtf8("btn75"));
        btn75->setGeometry(QRect(220, 160, 30, 30));
        btn75->setFont(font2);
        btn75->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn63 = new QPushButton(groupBox);
        btn63->setObjectName(QString::fromUtf8("btn63"));
        btn63->setGeometry(QRect(190, 130, 30, 30));
        btn63->setFont(font2);
        btn63->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn20 = new QPushButton(groupBox);
        btn20->setObjectName(QString::fromUtf8("btn20"));
        btn20->setGeometry(QRect(10, 40, 30, 30));
        btn20->setFont(font2);
        btn20->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btn87 = new QPushButton(groupBox);
        btn87->setObjectName(QString::fromUtf8("btn87"));
        btn87->setGeometry(QRect(580, 160, 30, 30));
        btn87->setFont(font2);
        btn87->setStyleSheet(QString::fromUtf8("background-image:url(none);"));
        btnClear = new QPushButton(CPrintMonthlyReport);
        btnClear->setObjectName(QString::fromUtf8("btnClear"));
        btnClear->setGeometry(QRect(320, 265, 61, 30));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\351\273\221\344\275\223"));
        font3.setPointSize(16);
        font3.setBold(false);
        font3.setWeight(50);
        btnClear->setFont(font3);
        btnClear->setStyleSheet(QString::fromUtf8("background-image:url(none);"));

        retranslateUi(CPrintMonthlyReport);

        QMetaObject::connectSlotsByName(CPrintMonthlyReport);
    } // setupUi

    void retranslateUi(QFrame *CPrintMonthlyReport)
    {
        CPrintMonthlyReport->setWindowTitle(QApplication::translate("CPrintMonthlyReport", "Frame", 0, QApplication::UnicodeUTF8));
        btn96->setText(QApplication::translate("CPrintMonthlyReport", "\345\217\226\346\266\210", 0, QApplication::UnicodeUTF8));
        btn99->setText(QApplication::translate("CPrintMonthlyReport", "\347\241\256\345\256\232", 0, QApplication::UnicodeUTF8));
        btnRes0->setText(QString());
        btnRes1->setText(QString());
        btnRes2->setText(QString());
        btnRes3->setText(QString());
        btnRes7->setText(QString());
        btnRes5->setText(QString());
        btnRes6->setText(QString());
        btnRes4->setText(QString());
        groupBox->setTitle(QString());
        btn35->setText(QString());
        btn2->setText(QString());
        btn32->setText(QString());
        btn44->setText(QString());
        btn39->setText(QString());
        btn38->setText(QString());
        btn47->setText(QString());
        btn11->setText(QString());
        btn22->setText(QString());
        btn33->setText(QString());
        btn21->setText(QString());
        btn4->setText(QString());
        btn74->setText(QString());
        btn76->setText(QString());
        btn43->setText(QString());
        btn28->setText(QString());
        btn60->setText(QString());
        btn29->setText(QString());
        btn68->setText(QString());
        btn65->setText(QString());
        btn71->setText(QString());
        btn72->setText(QString());
        btn49->setText(QString());
        btn30->setText(QString());
        btn42->setText(QString());
        btn19->setText(QString());
        btn34->setText(QString());
        btn61->setText(QString());
        btn79->setText(QString());
        btn25->setText(QString());
        btn45->setText(QString());
        btn56->setText(QString());
        btn78->setText(QString());
        btn83->setText(QString());
        btn55->setText(QString());
        btn7->setText(QString());
        btn5->setText(QString());
        btn69->setText(QString());
        btn13->setText(QString());
        btn36->setText(QString());
        btn15->setText(QString());
        btn18->setText(QString());
        btn8->setText(QString());
        btn31->setText(QString());
        btn14->setText(QString());
        btn27->setText(QString());
        btn9->setText(QString());
        btn57->setText(QString());
        btn48->setText(QString());
        btn51->setText(QString());
        btn67->setText(QString());
        btn52->setText(QString());
        btn77->setText(QString());
        btn0->setText(QString());
        btn40->setText(QString());
        btn53->setText(QString());
        btn6->setText(QString());
        btn81->setText(QString());
        btn46->setText(QString());
        btn16->setText(QString());
        btn66->setText(QString());
        btn26->setText(QString());
        btn64->setText(QString());
        btn24->setText(QString());
        btn62->setText(QString());
        btn84->setText(QString());
        btn86->setText(QString());
        btn12->setText(QString());
        btn58->setText(QString());
        btn3->setText(QString());
        btn82->setText(QString());
        btn23->setText(QString());
        btn37->setText(QString());
        btn80->setText(QString());
        btn50->setText(QString());
        btn70->setText(QString());
        btn73->setText(QString());
        btn1->setText(QString());
        btn17->setText(QString());
        btn41->setText(QString());
        btn85->setText(QString());
        btn54->setText(QString());
        btn59->setText(QString());
        btn10->setText(QString());
        btn75->setText(QString());
        btn63->setText(QString());
        btn20->setText(QString());
        btn87->setText(QString());
        btnClear->setText(QApplication::translate("CPrintMonthlyReport", "\346\270\205\351\231\244", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class CPrintMonthlyReport: public Ui_CPrintMonthlyReport {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PRINTMONTHLYREPORT_H
