// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSMSX wrapper class

class CSMSX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSMSX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6c701a8e, 0xefd, 0x4539, { 0x83, 0xd6, 0x3b, 0xde, 0xbc, 0xdd, 0x9c, 0x1f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long Init();
	long ConnectModem(LPCTSTR PortName, long BaudRate, LPCTSTR AccessCode);
	void DisconnectModem();
	void SetSend(BOOL SendFlag);
	void SetRecv(BOOL RecvFlag);
	long SendMsg(LPCTSTR DestNum, LPCTSTR Content, long MsgIndex);
	long SendListCount();
	BOOL ModemConnected();
	long RecvListCount();
	void RecvMsg(BSTR* PhoneNum, BSTR* Content, long* Year, long* Month, long* Day, long* Hour, long* Minute, long* Second);
};
